"""Adiciona modelos EstoqueLojaItem, ConfiguracaoServidor e status Personagem

Revision ID: b985a3560792
Revises: d1495bdc3dce
Create Date: 2025-04-14 09:08:33.054590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b985a3560792'
down_revision: Union[str, None] = 'd1495bdc3dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_servidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servidor_id', 'chave', name='_servidor_chave_uc')
    )
    op.create_index(op.f('ix_configuracoes_servidor_id'), 'configuracoes_servidor', ['id'], unique=False)
    op.create_index(op.f('ix_configuracoes_servidor_servidor_id'), 'configuracoes_servidor', ['servidor_id'], unique=False)
    op.create_table('estoque_loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_especifico', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servidor_id', 'item_id', name='_servidor_item_uc')
    )
    op.create_index(op.f('ix_estoque_loja_id'), 'estoque_loja', ['id'], unique=False)
    op.create_index(op.f('ix_estoque_loja_servidor_id'), 'estoque_loja', ['servidor_id'], unique=False)
    op.add_column('personagens', sa.Column('status', sa.Enum('ATIVO', 'APOSENTADO', name='statuspersonagem'), server_default='ativo', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personagens', 'status')
    op.drop_index(op.f('ix_estoque_loja_servidor_id'), table_name='estoque_loja')
    op.drop_index(op.f('ix_estoque_loja_id'), table_name='estoque_loja')
    op.drop_table('estoque_loja')
    op.drop_index(op.f('ix_configuracoes_servidor_servidor_id'), table_name='configuracoes_servidor')
    op.drop_index(op.f('ix_configuracoes_servidor_id'), table_name='configuracoes_servidor')
    op.drop_table('configuracoes_servidor')
    # ### end Alembic commands ###
